apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: live
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: strm/helloworld-http
          ports:
            - containerPort: 80
          env:
            # TODO add postgres credentials
            # TODO add public.url
            - name: BREVO_SECRET
              valueFrom:
                secretKeyRef:
                  name: sops-secrets
                  key: live.brevo.secret
