apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 1h
  path: ./infrastructure/cert-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: helm-repositories
  wait: true
  timeout: 5m
  resources:
    - namespace.yaml
    - release.yaml
    - cluster-issuer.yaml
