apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: postgres-controller
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/clusters/blue/infrastructure/postgres-controller
  prune: false
  wait: true
  dependsOn:
    - name: local-storage
