apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cloudnative-pg
  namespace: database
spec:
  repo: https://cloudnative-pg.github.io/charts
  chart: cloudnative-pg
  version: 0.23.0
  targetNamespace: database
  # valuesContent: |-
  #   image:
  #     repository: ghcr.io/cloudnative-pg/cloudnative-pg
  #     pullPolicy: IfNotPresent
  #     tag: "1.26.0"
  #   controllerManager:
  #     create: true
  #     watchNamespace: ""
  #     logLevel: info
  #     resources:
  #       limits:
  #         cpu: 200m
  #         memory: 256Mi
  #       requests:
  #         cpu: 100m
  #         memory: 128Mi
  #   serviceAccount:
  #     create: true
  #   rbac:
  #     create: true
  #   webhook:
  #     create: true
