apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudnative-pg
  namespace: database
spec:
  interval: 60m
  chart:
    spec:
      chart: cloudnative-pg
      version: "0.23.0"
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
        namespace: database
      interval: 60m
  # values:
  #   image:
  #     repository: ghcr.io/cloudnative-pg/cloudnative-pg
  #     pullPolicy: IfNotPresent
  #     tag: "1.26.0"
  #   controllerManager:
  #     create: true
  #     watchNamespace: ""
  #     logLevel: info
  #     resources:
  #       limits:
  #         cpu: 200m
  #         memory: 256Mi
  #       requests:
  #         cpu: 100m
  #         memory: 128Mi
  #   serviceAccount:
  #     create: true
  #   rbac:
  #     create: true
  #   webhook:
  #     create: true
