flux:
  github_pat_token: ENC[AES256_GCM,data:pi8CMurZMn8uCzcJtgiZPhUVtNerx0VhLJjVCHJJ5hJoRsz0Tc6P/w==,iv:8TeZFtSSPpUn9EGZj9HOrLxTScE/kq4SFNnUPIsWdQs=,tag:sPNaVDV5SUSL3va1Drik6g==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1nv246qytt62sc6k6773lpjvkfk8ez48da0u64cs6vufg8qpzpdvqrprp0t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMSFVycExON0tLbDJCSXVW
        SE83N2ZkT2hJWEoySHlscVFSZTBocitWUkR3ClVGOWo4N1VkVDIvZEdjNU9odm1J
        djJGcDVZMGp0NzJJZm9iMzJJZkt2eW8KLS0tIFVDbDc0YndqWHduVnJNMnREcmVL
        ZG5tdmVxSnhTK3JrU1FZQWc4V1pEWmsK3JHJ/C8GvRXUi5/cWCEeMW/sdEzoUPAl
        j/5KspYftp4gYl05j0+WYaE7fbrb0GT0JKI/qwbYlfFtG/eFBVodUQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-30T01:45:35Z"
  mac: ENC[AES256_GCM,data:Dj7PNG0JMvIvknjFgTwEy1WNor8ARBhhPRdkEe4Hfy856rZuGzJAgbBDRmegNaikL7CqeAh/AVkQWH1vwgjOVTlqZ1raJY8r1++ANU0WKRC3Edhto8A84GhUfHdHU9R9+laM+lNOUUv51oy76gvE6k6dcPWMcA9PsqlfqOiuTsc=,iv:iKM5QYnIDc9EC4fYJKpg+xhX8B2vm9KDelvrSENwDxM=,tag:UF6l4EqseIeScX9xYBYZEw==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.4
