apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - database.yaml
  - deployment.yaml
  - namespace.yaml
  - service.yaml
  - ../../../infrastructure/base/deployment/policy.live.yaml
