---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-ip-controller
  namespace: flux-system
spec:
  path: ../infrastructure/external-ip-controller
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: caddy
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: external-ip-controller
  path: ../infrastructure/caddy
  prune: true
