apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - caddy.yaml
  # - helm-repos/ingress-nginx.yaml
  # - ingress-nginx/namespace.yaml
  # - ingress-nginx/release.yaml
  # - helm-repos/cert-manager.yaml
  # - cert-manager/namespace.yaml
  # - cert-manager/release.yaml
  # - cert-manager/cluster-issuer.yaml
