apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - external-ip-controller/all.yaml
  # - servicelb/all.yaml
  - caddy
  - local-storage
  # - csi-hetzner
