---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: postgres-controller
  namespace: flux-system
spec:
  path: ./postgres-controller
  # prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: postgres-cluster
  namespace: flux-system
spec:
  dependsOn:
    - name: postgres-controller
  path: ./postgres-cluster
  # prune: true
