apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: live-backend
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/apps/live/backend
  prune: true
  dependsOn:
    - name: postgres-cluster
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: test-backend
#   namespace: flux-system
# spec:
#   interval: 10m
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   path: ./flux/apps/test/backend
#   prune: true
#   dependsOn:
#     - name: postgres-cluster
