apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sops-secrets
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./terraform/secrets.enc.yaml
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
