apiVersion: v1
kind: ConfigMap
metadata:
  name: local-path-config
  namespace: storage-system
data:
  config.json: |-
    {
      "nodePathMap":[
        {
          "node":"DEFAULT_PATH_FOR_NON_LISTED_NODES",
          "paths":["/var/local-path-provisioner"]
        }
      ]
    } 