apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hello-world-secrets
  namespace: demo
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: sops-secret-store
  target:
    name: hello-world-secrets
    creationPolicy: Owner
  data:
    - secretKey: FOO
      remoteRef:
        key: live.app.foo
    - secretKey: BAR
      remoteRef:
        key: live.app.foo
