apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - config.yaml
  - pv.yaml
  - pvc.yaml
  - service.yaml
  - deployment.yaml
configMapGenerator:
  - name: caddy
    namespace: infra
    files:
      - Caddyfile
