apiVersion: v1
kind: PersistentVolume
metadata:
  name: caddy-data-volume
  namespace: infra
  labels:
    app: caddy
    type: local
spec:
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  hostPath:
    path: /var/local-path-provisioner/caddy
