apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: caddy-data-volume-claim
  namespace: ingress
  labels:
    app: caddy
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 50Mi
