apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: caddy
  namespace: caddy-system
spec:
  interval: 5m
  chart:
    spec:
      chart: caddy-ingress-controller
      version: ">=0.2.0"
      sourceRef:
        kind: HelmRepository
        name: caddy
        namespace: flux-system
  values:
    ingressController:
      config:
        email: tcurdt@vafer.org
        onDemandTLS: true 