apiVersion: v1
kind: Service
metadata:
  namespace: ingress
  name: caddy
  labels:
    app: caddy
  annotations:
    external-ip-interface: enp1s0
spec:
  selector:
    app: caddy

  type: NodePort
  # externalIPs:
  #   - 138.199.151.168
  #   - 159.69.52.101
  ports:
    - port: 80
      name: http
      targetPort: 80
      protocol: TCP
    - port: 443
      name: https
      targetPort: 443
      protocol: TCP

  # type: LoadBalancer
  # externalTrafficPolicy: Local
  # # loadBalancerIP:
  # ports:
  #   - name: http
  #     port: 80
  #   - name: https
  #     port: 443
