apiVersion: v1
kind: Service
metadata:
  namespace: infra
  name: caddy
  labels:
    app: caddy
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  # loadBalancerIP:
  selector:
    app: caddy
  ports:
    - name: http
      port: 80
    - name: https
      port: 443
