apiVersion: v1
kind: Service
metadata:
  namespace: infra
  name: caddy
  labels:
    app: caddy
spec:
  selector:
    app: caddy

  type: NodePort
  externalIPs:
    - 138.199.151.168
    - 159.69.52.101
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP

  # type: NodePort
  # externalIPs:
  #   - 159.69.52.101
  # ports:
  #   - port: 80
  #     name: http
  #     targetPort: 80
  #     protocol: TCP
  #   - port: 443
  #     name: https
  #     targetPort: 443
  #     protocol: TCP

  # type: LoadBalancer
  # externalTrafficPolicy: Local
  # # loadBalancerIP:
  # ports:
  #   - name: http
  #     port: 80
  #   - name: https
  #     port: 443
