# clusters/foo/flux-system/kustomize-controller.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: secrets
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age # This just references the secret we created manually

# apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
# kind: Kustomization
# metadata:
#   name: secrets
#   namespace: flux-system
# spec:
#   interval: 1m0s
#   path: ./secrets
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   decryption:
#     provider: sops
#     secretRef:
#       name: sops-age
