name: ci

on:
  workflow_dispatch:
  push:
    branches:
      - "*"
    paths-ignore:
      - "docs/**"
      - "README.md"

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify
        run: |
          cd flux
          bash scripts/verify.sh
