name: ci

on:
  workflow_dispatch:
  push:
    branches:
      - "*"
    paths-ignore:
      - "docs/**"
      - "README.md"

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install yq
        run: |
          sudo apt-get install -y yq

      - name: Install kustomize
        uses: jaxxstorm/action-install-gh-release@v1.10.0
        with:
          repo: kubernetes-sigs/kustomize

      - name: Install kubeconform
        uses: jaxxstorm/action-install-gh-release@v1.10.0
        with:
          repo: yannh/kubeconform

      - name: Versions
        run: |
          yq --version
          kustomize version
          kubeconform -v

      - name: Verify
        run: |
          cd flux
          bash scripts/validate.sh
