apiVersion: ENC[AES256_GCM,data:DAY=,iv:WfvYAbO1IkbTbPsNQ5+BOinYg3kGMZGgujDDiZncUVM=,tag:V/AuyX9r6weXqknJqfnhRw==,type:str]
data:
    .dockerconfigjson: ENC[AES256_GCM,data:/xPNz14fymM3xDb3iJafCQHO88PeqQ8/8ETt2Bc/DJGvAKM2lm2Yg0klUVKfZad/MP9JAhjBPwgfS0FgJFnXMemQrfI18MZ1+mrrK+qZcAMCB9qbdpd7bOu9FgH9khCRhxDFGk2cJXxeWDC5dXaMBn5QC6h4hVTScFfDP6AEH5Zmxio1+VgiUZcVinZ6lQ2j67OA61olZbvVawCDmxql5DmPSPtyy+8CflfxoZ9DM1Veus72ZALCRQZv9kSwq/7/,iv:3h+uG8aRiHFkNVFinap5smDN6iOnOF/xe1oH1jmbe6M=,tag:pivtN3DXKTQMJceDUcwNAw==,type:str]
kind: ENC[AES256_GCM,data:Aa/NmoTe,iv:YGNxnc5uy3ErLYN/my40oWGhjlewHPAH8WrfAtf43Gw=,tag:Dl6KRLB4zChNTmGPkQgNcg==,type:str]
metadata:
    creationTimestamp: null
    name: ENC[AES256_GCM,data:IP7VzXmIRImHnw==,iv:6hfrRqpHTG+IFzOyw6X2Tcpye7HZ3LG9nY60IWnAaOY=,tag:bbSWGPte6kLy6TRN0Ddavw==,type:str]
type: ENC[AES256_GCM,data:QItHIqnxBEhm4rP6ks7CsJsbeX7cX5DTfv7wDBND,iv:zYitl9tQGZQTEWta7HKs22iGbR1BPRV8UwygRPWjrpY=,tag:ATZRyCvKrMAMY2V7Ije5RQ==,type:str]
sops:
    age:
        - recipient: age1nv246qytt62sc6k6773lpjvkfk8ez48da0u64cs6vufg8qpzpdvqrprp0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKK0tueFdmTDRGYXAwODhz
            RFNYaURhMVlTRU5uRlg4T3R1S3pUbmJBZHhJClpwVEJWelZ5eXJvUmhrU0NlQWFs
            V1VoMnd6WDk2NG9PbGJ0bWRkRExoTDAKLS0tIFFmbTkyN2czS1o4YnZOUkIyV21H
            VHJFMC9Sb0dZYVo3SmU2My9LcTF1Wm8K2VFBLIMzO8+rVtUkiniaAf2sTuAsTmle
            HdDJW+lQhBgC6YM8IL+ml/rv83+sAGCWmHOaz3TvRlqn19qSuutE2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-16T22:27:24Z"
    mac: ENC[AES256_GCM,data:sXo1yUlhhwAbJAQMnD4vHvL/REVSXe2pI6yPU2zMCad1KpYVoaGTtqUfRyy6uO+rR5evZwdvH+F6FJCD9zDtXyjH4gsN4gNm6w2HUhYlI0+X4AsY4BNlnGvko/7RvExPXrmbugM/7Eh8owIoc+7WAcGXNwltlEm/ndjaoSWGKI4=,iv:TzywVhttoHLUdkZY/vbxK3LV7XgnPkZ9jGuNVjViV4M=,tag:+7ke8VZ7sdEZO/7fibEhiA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.1
