apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - enc.flux.githubapp.yaml
  - enc.flux.github.yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: live
resources:
  - enc.oci.github.yaml
secretGenerator:
  - name: dotenv
    envs:
      - enc.env.live
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: test
resources:
  - enc.oci.github.yaml
secretGenerator:
  - name: dotenv
    envs:
      - enc.env.test
