apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: policy-live
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: backend-repository
  filterTags:
    pattern: "^branch-live-(?P<ts>[0-9]+)$"
  policy:
    numerical:
      order: asc
