apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: backend-repository
  namespace: flux-system
spec:
  image: ghcr.io/edkimo/backend
  interval: 1m
  secretRef:
    name: oci-github
